### ISSUE TITLE
Make simple version of mkTPWS

### ISSUE THREAD

**Issue by kfrasier** [ScrippsWhaleAcoustics/DetEdit#20]
Simple version of mkTPWS for detEdit 2014+

**Comment by kfrasier** [comment]
@asolsonaberga here is the documentation for the two functions I'm planning to write for this ticket. (Documentation for one, example script for the other, really).

Please review carefully and let me know if this is what you want. 
I've marked things that need special consideration with ***.

[make_TPWS.zip](https://github.com/ScrippsWhaleAcoustics/Grateful-DetEdit/files/1996602/make_TPWS.zip)

**Comment by asolsonaberga** [comment]
% *** Alba, this is important to decide on. I think it would be best to
% force the transfer function to be included in MPP. This greatly
% simplifies the handling of all the crazy ways people normalize their
% data, and will reduce the complexity of detEdit. BUT you have to be ok
% with it. This is easy for me to say, because I already do it this way,
% but you may have reasons why this isn't possible?? ***

I think this is the most appropriated way. I don't see any reason why this wouldn't be possible. As you specified, they can always give a single number like "0" if they don't want to apply a tf. However, they will not be able to use the parameters that we provide it for the different species. They should just be aware of this. 

Regarding time series, I guess you want to be able to identify which one needs the padding and peak alignment or not by identifying if what they give is a cell array or 2D matrix. Are you using cell arrays now in your code to make your TPWS? Looks good to me but just thinking if this will be too confusing for people not used to work with different types of variables in Matlab.

**Comment by kfrasier** [comment]
Well I was thinking about Simone's detector, which outputs cell arrays of time series, I think?
At least it used to, because the segment lengths were different. I don't know how common that is.
I agree that it adds extra complexity and I don't mind limiting it to matrix form if that seems ok to you.

If people hand in a matrix of time series, do you think it's ok to just leave as is, or should we check that the signals are aligned by maximum amplitude? I think it's important that they are aligned, because detEdit averages them, so it will get weird if they aren't. 
But I also don't want to do crazy unexpected things to people's data, you know? At least not more than necessary :/

**Comment by asolsonaberga** [comment]
I would say limiting it to matrix makes everything more clear. In terms of aligning the maximums, I would suggest giving it as an option, in my case I didn't align because I had to deal with different peaks within a click. By default I would put it as aligned, bad give the option of not doing it.
